package upeu.edu.pe.mspersona.loaders;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import upeu.edu.pe.mspersona.entity.Persona;
import upeu.edu.pe.mspersona.repository.PersonaRepository;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Configuration
public class PersonaDataLoader {

    @Bean
    public CommandLineRunner loadPersonas(PersonaRepository personaRepository) {
        return args -> {
            // Verificar si existen personas en la base de datos
            if (personaRepository.count() == 0) {

                // Crear cuatro personas con datos de ejemplo
                Persona persona1 = new Persona();
                persona1.setNombres("Juan");
                persona1.setApellido_paterno("Pérez");
                persona1.setApellido_materno("García");
                persona1.setFecha_nacimiento(LocalDate.of(1990, 5, 20));
                persona1.setGenero("Masculino");
                persona1.setNacionalidad("Peruana");
                persona1.setTipoDocumento("DNI");
                persona1.setNumeroDocumento("12345678");
                persona1.setDireccion("Av. Siempre Viva 123");
                persona1.setCiudad("Lima");
                persona1.setDepartamento("Lima");
                persona1.setPais("Perú");
                persona1.setProvincia("Lima");
                persona1.setTelefono("987654321");
                persona1.setEmail("juan.perez@example.com");
                persona1.setEstadoCivil("Soltero");
                persona1.setFotoPerfil("Perfil.jpg");
                persona1.setTipoSangre("O+");
                persona1.setContactoEmergenciaNombre("María Pérez");
                persona1.setContactoEmergenciaTelefono("912345678");
                persona1.setContactoEmergenciaEmail("maria.perez@example.com");
                persona1.setContactoEmergenciaDireccion("Av. Siempre Viva 124");
                persona1.setContactoEmergenciaCiudad("Lima");
                persona1.setContactoEmergenciaParentesco("Hermana");
                persona1.setIdUsuario(1L);

                Persona persona2 = new Persona();
                persona2.setNombres("Ana");
                persona2.setApellido_paterno("Lopez");
                persona2.setApellido_materno("Martínez");
                persona2.setFecha_nacimiento(LocalDate.of(1985, 3, 15));
                persona2.setGenero("Femenino");
                persona2.setNacionalidad("Peruana");
                persona2.setTipoDocumento("DNI");
                persona2.setNumeroDocumento("87654321");
                persona2.setDireccion("Calle Falsa 456");
                persona2.setCiudad("Arequipa");
                persona2.setDepartamento("Arequipa");
                persona2.setPais("Perú");
                persona2.setProvincia("Arequipa");
                persona2.setTelefono("998877665");
                persona2.setEmail("ana.lopez@example.com");
                persona2.setEstadoCivil("Casada");
                persona2.setFotoPerfil("Perfil.jpg");
                persona2.setTipoSangre("A+");
                persona2.setContactoEmergenciaNombre("José Lopez");
                persona2.setContactoEmergenciaTelefono("987654321");
                persona2.setContactoEmergenciaEmail("jose.lopez@example.com");
                persona2.setContactoEmergenciaDireccion("Calle Falsa 457");
                persona2.setContactoEmergenciaCiudad("Arequipa");
                persona2.setContactoEmergenciaParentesco("Esposo");
                persona2.setIdUsuario(2L);

                Persona persona3 = new Persona();
                persona3.setNombres("Carlos");
                persona3.setApellido_paterno("Sánchez");
                persona3.setApellido_materno("Torres");
                persona3.setFecha_nacimiento(LocalDate.of(1992, 7, 10));
                persona3.setGenero("Masculino");
                persona3.setNacionalidad("Peruana");
                persona3.setTipoDocumento("DNI");
                persona3.setNumeroDocumento("12348765");
                persona3.setDireccion("Jr. Los Pinos 789");
                persona3.setCiudad("Trujillo");
                persona3.setDepartamento("La Libertad");
                persona3.setPais("Perú");
                persona3.setProvincia("Trujillo");
                persona3.setTelefono("996655443");
                persona3.setEmail("carlos.sanchez@example.com");
                persona3.setEstadoCivil("Soltero");
                persona3.setFotoPerfil("Perfil.jpg");
                persona3.setTipoSangre("B+");
                persona3.setContactoEmergenciaNombre("Luisa Sánchez");
                persona3.setContactoEmergenciaTelefono("965432109");
                persona3.setContactoEmergenciaEmail("luisa.sanchez@example.com");
                persona3.setContactoEmergenciaDireccion("Jr. Los Pinos 790");
                persona3.setContactoEmergenciaCiudad("Trujillo");
                persona3.setContactoEmergenciaParentesco("Hermana");
                persona3.setIdUsuario(3L);

                Persona persona4 = new Persona();
                persona4.setNombres("María");
                persona4.setApellido_paterno("Gómez");
                persona4.setApellido_materno("Fernández");
                persona4.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona4.setGenero("Femenino");
                persona4.setNacionalidad("Peruana");
                persona4.setTipoDocumento("DNI");
                persona4.setNumeroDocumento("23456789");
                persona4.setDireccion("Calle Verdadera 321");
                persona4.setCiudad("Cusco");
                persona4.setDepartamento("Cusco");
                persona4.setPais("Perú");
                persona4.setProvincia("Cusco");
                persona4.setTelefono("944556677");
                persona4.setEmail("maria.gomez@example.com");
                persona4.setEstadoCivil("Divorciada");
                persona4.setFotoPerfil("Perfil.jpg");
                persona4.setTipoSangre("AB+");
                persona4.setContactoEmergenciaNombre("Pedro Gómez");
                persona4.setContactoEmergenciaTelefono("993322445");
                persona4.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona4.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona4.setContactoEmergenciaCiudad("Cusco");
                persona4.setContactoEmergenciaParentesco("Hermano");
                persona4.setIdUsuario(4L);

                Persona persona5 = new Persona();
                persona5.setNombres("María");
                persona5.setApellido_paterno("Gómez");
                persona5.setApellido_materno("Fernández");
                persona5.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona5.setGenero("Femenino");
                persona5.setNacionalidad("Peruana");
                persona5.setTipoDocumento("DNI");
                persona5.setNumeroDocumento("23456789");
                persona5.setDireccion("Calle Verdadera 321");
                persona5.setCiudad("Cusco");
                persona5.setDepartamento("Cusco");
                persona5.setPais("Perú");
                persona5.setProvincia("Cusco");
                persona5.setTelefono("944556677");
                persona5.setEmail("maria.gomez@example.com");
                persona5.setEstadoCivil("Divorciada");
                persona5.setFotoPerfil("Perfil.jpg");
                persona5.setTipoSangre("AB+");
                persona5.setContactoEmergenciaNombre("Pedro Gómez");
                persona5.setContactoEmergenciaTelefono("993322445");
                persona5.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona5.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona5.setContactoEmergenciaCiudad("Cusco");
                persona5.setContactoEmergenciaParentesco("Hermano");
                persona5.setIdUsuario(5L);

                Persona persona6 = new Persona();
                persona6.setNombres("María");
                persona6.setApellido_paterno("Gómez");
                persona6.setApellido_materno("Fernández");
                persona6.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona6.setGenero("Femenino");
                persona6.setNacionalidad("Peruana");
                persona6.setTipoDocumento("DNI");
                persona6.setNumeroDocumento("23456789");
                persona6.setDireccion("Calle Verdadera 321");
                persona6.setCiudad("Cusco");
                persona6.setDepartamento("Cusco");
                persona6.setPais("Perú");
                persona6.setProvincia("Cusco");
                persona6.setTelefono("944556677");
                persona6.setEmail("maria.gomez@example.com");
                persona6.setEstadoCivil("Divorciada");
                persona6.setFotoPerfil("Perfil.jpg");
                persona6.setTipoSangre("AB+");
                persona6.setContactoEmergenciaNombre("Pedro Gómez");
                persona6.setContactoEmergenciaTelefono("993322445");
                persona6.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona6.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona6.setContactoEmergenciaCiudad("Cusco");
                persona6.setContactoEmergenciaParentesco("Hermano");
                persona6.setIdUsuario(6L);

                Persona persona7 = new Persona();
                persona7.setNombres("María");
                persona7.setApellido_paterno("Gómez");
                persona7.setApellido_materno("Fernández");
                persona7.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona7.setGenero("Femenino");
                persona7.setNacionalidad("Peruana");
                persona7.setTipoDocumento("DNI");
                persona7.setNumeroDocumento("23456789");
                persona7.setDireccion("Calle Verdadera 321");
                persona7.setCiudad("Cusco");
                persona7.setDepartamento("Cusco");
                persona7.setPais("Perú");
                persona7.setProvincia("Cusco");
                persona7.setTelefono("944556677");
                persona7.setEmail("maria.gomez@example.com");
                persona7.setEstadoCivil("Divorciada");
                persona7.setFotoPerfil("Perfil.jpg");
                persona7.setTipoSangre("AB+");
                persona7.setContactoEmergenciaNombre("Pedro Gómez");
                persona7.setContactoEmergenciaTelefono("993322445");
                persona7.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona7.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona7.setContactoEmergenciaCiudad("Cusco");
                persona7.setContactoEmergenciaParentesco("Hermano");
                persona7.setIdUsuario(7L);

                Persona persona8 = new Persona();
                persona8.setNombres("María");
                persona8.setApellido_paterno("Gómez");
                persona8.setApellido_materno("Fernández");
                persona8.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona8.setGenero("Femenino");
                persona8.setNacionalidad("Peruana");
                persona8.setTipoDocumento("DNI");
                persona8.setNumeroDocumento("23456789");
                persona8.setDireccion("Calle Verdadera 321");
                persona8.setCiudad("Cusco");
                persona8.setDepartamento("Cusco");
                persona8.setPais("Perú");
                persona8.setProvincia("Cusco");
                persona8.setTelefono("944556677");
                persona8.setEmail("maria.gomez@example.com");
                persona8.setEstadoCivil("Divorciada");
                persona8.setFotoPerfil("Perfil.jpg");
                persona8.setTipoSangre("AB+");
                persona8.setContactoEmergenciaNombre("Pedro Gómez");
                persona8.setContactoEmergenciaTelefono("993322445");
                persona8.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona8.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona8.setContactoEmergenciaCiudad("Cusco");
                persona8.setContactoEmergenciaParentesco("Hermano");
                persona8.setIdUsuario(8L);

                Persona persona9 = new Persona();
                persona9.setNombres("María");
                persona9.setApellido_paterno("Gómez");
                persona9.setApellido_materno("Fernández");
                persona9.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona9.setGenero("Femenino");
                persona9.setNacionalidad("Peruana");
                persona9.setTipoDocumento("DNI");
                persona9.setNumeroDocumento("23456789");
                persona9.setDireccion("Calle Verdadera 321");
                persona9.setCiudad("Cusco");
                persona9.setDepartamento("Cusco");
                persona9.setPais("Perú");
                persona9.setProvincia("Cusco");
                persona9.setTelefono("944556677");
                persona9.setEmail("maria.gomez@example.com");
                persona9.setEstadoCivil("Divorciada");
                persona9.setFotoPerfil("Perfil.jpg");
                persona9.setTipoSangre("AB+");
                persona9.setContactoEmergenciaNombre("Pedro Gómez");
                persona9.setContactoEmergenciaTelefono("993322445");
                persona9.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona9.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona9.setContactoEmergenciaCiudad("Cusco");
                persona9.setContactoEmergenciaParentesco("Hermano");
                persona9.setIdUsuario(9L);

                Persona persona10 = new Persona();
                persona10.setNombres("María");
                persona10.setApellido_paterno("Gómez");
                persona10.setApellido_materno("Fernández");
                persona10.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona10.setGenero("Femenino");
                persona10.setNacionalidad("Peruana");
                persona10.setTipoDocumento("DNI");
                persona10.setNumeroDocumento("23456789");
                persona10.setDireccion("Calle Verdadera 321");
                persona10.setCiudad("Cusco");
                persona10.setDepartamento("Cusco");
                persona10.setPais("Perú");
                persona10.setProvincia("Cusco");
                persona10.setTelefono("944556677");
                persona10.setEmail("maria.gomez@example.com");
                persona10.setEstadoCivil("Divorciada");
                persona10.setFotoPerfil("Perfil.jpg");
                persona10.setTipoSangre("AB+");
                persona10.setContactoEmergenciaNombre("Pedro Gómez");
                persona10.setContactoEmergenciaTelefono("993322445");
                persona10.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona10.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona10.setContactoEmergenciaCiudad("Cusco");
                persona10.setContactoEmergenciaParentesco("Hermano");
                persona10.setIdUsuario(10L);

                Persona persona11 = new Persona();
                persona11.setNombres("María");
                persona11.setApellido_paterno("Gómez");
                persona11.setApellido_materno("Fernández");
                persona11.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona11.setGenero("Femenino");
                persona11.setNacionalidad("Peruana");
                persona11.setTipoDocumento("DNI");
                persona11.setNumeroDocumento("23456789");
                persona11.setDireccion("Calle Verdadera 321");
                persona11.setCiudad("Cusco");
                persona11.setDepartamento("Cusco");
                persona11.setPais("Perú");
                persona11.setProvincia("Cusco");
                persona11.setTelefono("944556677");
                persona11.setEmail("maria.gomez@example.com");
                persona11.setEstadoCivil("Divorciada");
                persona11.setFotoPerfil("Perfil.jpg");
                persona11.setTipoSangre("AB+");
                persona11.setContactoEmergenciaNombre("Pedro Gómez");
                persona11.setContactoEmergenciaTelefono("993322445");
                persona11.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona11.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona11.setContactoEmergenciaCiudad("Cusco");
                persona11.setContactoEmergenciaParentesco("Hermano");
                persona11.setIdUsuario(11L);

                Persona persona12 = new Persona();
                persona12.setNombres("María");
                persona12.setApellido_paterno("Gómez");
                persona12.setApellido_materno("Fernández");
                persona12.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona12.setGenero("Femenino");
                persona12.setNacionalidad("Peruana");
                persona12.setTipoDocumento("DNI");
                persona12.setNumeroDocumento("23456789");
                persona12.setDireccion("Calle Verdadera 321");
                persona12.setCiudad("Cusco");
                persona12.setDepartamento("Cusco");
                persona12.setPais("Perú");
                persona12.setProvincia("Cusco");
                persona12.setTelefono("944556677");
                persona12.setEmail("maria.gomez@example.com");
                persona12.setEstadoCivil("Divorciada");
                persona12.setFotoPerfil("Perfil.jpg");
                persona12.setTipoSangre("AB+");
                persona12.setContactoEmergenciaNombre("Pedro Gómez");
                persona12.setContactoEmergenciaTelefono("993322445");
                persona12.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona12.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona12.setContactoEmergenciaCiudad("Cusco");
                persona12.setContactoEmergenciaParentesco("Hermano");
                persona12.setIdUsuario(12L);

                Persona persona13 = new Persona();
                persona13.setNombres("María");
                persona13.setApellido_paterno("Gómez");
                persona13.setApellido_materno("Fernández");
                persona13.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona13.setGenero("Femenino");
                persona13.setNacionalidad("Peruana");
                persona13.setTipoDocumento("DNI");
                persona13.setNumeroDocumento("23456789");
                persona13.setDireccion("Calle Verdadera 321");
                persona13.setCiudad("Cusco");
                persona13.setDepartamento("Cusco");
                persona13.setPais("Perú");
                persona13.setProvincia("Cusco");
                persona13.setTelefono("944556677");
                persona13.setEmail("maria.gomez@example.com");
                persona13.setEstadoCivil("Divorciada");
                persona13.setFotoPerfil("Perfil.jpg");
                persona13.setTipoSangre("AB+");
                persona13.setContactoEmergenciaNombre("Pedro Gómez");
                persona13.setContactoEmergenciaTelefono("993322445");
                persona13.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona13.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona13.setContactoEmergenciaCiudad("Cusco");
                persona13.setContactoEmergenciaParentesco("Hermano");
                persona13.setIdUsuario(13L);

                Persona persona14 = new Persona();
                persona14.setNombres("María");
                persona14.setApellido_paterno("Gómez");
                persona14.setApellido_materno("Fernández");
                persona14.setFecha_nacimiento(LocalDate.of(1988, 12, 5));
                persona14.setGenero("Femenino");
                persona14.setNacionalidad("Peruana");
                persona14.setTipoDocumento("DNI");
                persona14.setNumeroDocumento("23456789");
                persona14.setDireccion("Calle Verdadera 321");
                persona14.setCiudad("Cusco");
                persona14.setDepartamento("Cusco");
                persona14.setPais("Perú");
                persona14.setProvincia("Cusco");
                persona14.setTelefono("944556677");
                persona14.setEmail("maria.gomez@example.com");
                persona14.setEstadoCivil("Divorciada");
                persona14.setFotoPerfil("Perfil.jpg");
                persona14.setTipoSangre("AB+");
                persona14.setContactoEmergenciaNombre("Pedro Gómez");
                persona14.setContactoEmergenciaTelefono("993322445");
                persona14.setContactoEmergenciaEmail("pedro.gomez@example.com");
                persona14.setContactoEmergenciaDireccion("Calle Verdadera 322");
                persona14.setContactoEmergenciaCiudad("Cusco");
                persona14.setContactoEmergenciaParentesco("Hermano");
                persona14.setIdUsuario(14L);

                // Guardar personas en la base de datos
                personaRepository.saveAll(List.of(persona1, persona2, persona3, persona4, persona5, persona6, persona7, persona8, persona9, persona10, persona11, persona12, persona13, persona14));

                System.out.println("Personas iniciales creadas correctamente.");
            }
        };
    }
}
